name: test_intro_slide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.2

  freezed_annotation: ^2.2.0

  hooks_riverpod: ^2.1.1
  intro_slider: ^4.2.0
  json_annotation: ^4.7.0

  shared_preferences: ^2.1.0

dev_dependencies:

  build_runner: ^2.3.2

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.2.1

  json_serializable: ^6.5.4

flutter:

  uses-material-design: true
